### ISSUE TITLE
사도가 있어도 사도 미발견이 출력되면서 캐시 클리어를 시도합니다.

### ISSUE THREAD

**Issue by duawowns** [Kimhhhhhh/Trickal-Revive-reroll#2]
![image](https://github.com/Kimhhhhhh/Trickal-Revive-reroll/assets/66714118/bc35b0bf-fca4-458b-833f-94c986283dac)

$ macro.exe 5556 0
already connected to 127.0.0.1:5556
약관 0s 5556
볼잡기 9s 5556
이름 34s 5556
이름 38s 5556
속성 319s 5556
배속 367s 5556
lock 376s 5556
getMail 527s 5556
Gacha 1 5556
Gacha 2 5556
Gacha 3 5556
Gacha 4 5556
Gacha 5 5556
change to normal gacha 5556
Gacha 6 5556
Gacha 7 5556
Gacha 8 5556
Gacha 9 5556
Gacha 10 5556
Gacha 11 5556
Gacha End 5556
sadoCheck Enter
사도 OCR 결과 : []
발견 사도 : 0
사도 미발견
약관 12s 5556
볼잡기 21s 5556
이름 44s 5556
속성 319s 5556
배속 368s 5556
lock 377s 5556
getMail 515s 5556
Gacha 1 5556
Gacha 2 5556
Gacha 3 5556
Gacha 4 5556
Gacha 5 5556
change to normal gacha 5556
Gacha 6 5556
Gacha 7 5556
Gacha 8 5556
Gacha 9 5556
Gacha 10 5556
Gacha 11 5556
Gacha End 5556
sadoCheck Enter
사도 OCR 결과 : [1]
발견 사도 : 0
사도 미발견

**Comment by Kimhhhhhh** [comment]
OCR 방식이 컴퓨터 마다 편차가 있는 것 같습니다. 이미지 인식 방식으로 사도 확인 과정을 변경했습니다. 1.0.3 버젼을 사용해주세요.
