### ISSUE TITLE
1.08에서 Trojan:Win32/Wacatac.B!ml 발견되었다고...

### ISSUE THREAD

**Issue by A2Ring** [Kimhhhhhh/Trickal-Revive-reroll#3]
1.0.7에서는 안그랬는데...
![2023-10-02 15 23 28](https://github.com/Kimhhhhhh/Trickal-Revive-reroll/assets/28779061/fe83d28c-b1d4-4c87-a2d3-7aec584f4d76)

**Comment by A2Ring** [comment]
그리고 픽업말고 그냥 사도 뽑기로도 할수 있는 옵션을 추가해주실순없나요?
픽업사도는 엘시드얻지 못해서...

**Comment by A2Ring** [comment]
그리고 1.0.7 쓰는중인데 초보뽑기한 이후 바로 리세하네요...

**Comment by Kimhhhhhh** [comment]
그리고 픽업말고 그냥 사도 뽑기로도 할수 있는 옵션을 추가해주실순없나요?
> 이미 상시 뽑을 하는 기능이 있습니다.
